### ISSUE TITLE
dmatrix() issue in python 3.6.7

### ISSUE THREAD

**Issue by garzillo** [pydata/patsy#136]
Here's a minimally reproducible example for a bug I'm experiencing with python 3.6.7. 

I also tried the exact same thing on 3.6.0 and 3.6.3 and it worked without issue

import pandas as pd
from patsy import dmatrix

X = {
    'a': [2, 3, 4, 5],
    'b': [1, 0, 0, 1],
    'c': [0, 1, 1, 0],
    'd': [1, 0, 1, 0],
    'e': [0, 1, 0, 1]
}

X = pd.DataFrame(X)
formula = '0+a:c+a:d+a:e+b:c+b:d+b:e'

m = dmatrix(formula, data=X, return_type='dataframe')

This returns the following:

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alberto/.pyenv/versions/patsy/lib/python3.6/site-packages/patsy/highlevel.py", line 291, in dmatrix
    NA_action, return_type)
  File "/home/alberto/.pyenv/versions/patsy/lib/python3.6/site-packages/patsy/highlevel.py", line 165, in _do_highlevel_design
    NA_action)
  File "/home/alberto/.pyenv/versions/patsy/lib/python3.6/site-packages/patsy/highlevel.py", line 62, in _try_incr_builders
    formula_like = ModelDesc.from_formula(formula_like)
  File "/home/alberto/.pyenv/versions/patsy/lib/python3.6/site-packages/patsy/desc.py", line 164, in from_formula
    tree = parse_formula(tree_or_string)
  File "/home/alberto/.pyenv/versions/patsy/lib/python3.6/site-packages/patsy/parse_formula.py", line 148, in parse_formula
    _atomic_token_types)
  File "/home/alberto/.pyenv/versions/patsy/lib/python3.6/site-packages/patsy/infix_parser.py", line 210, in infix_parse
    for token in token_source:
  File "/home/alberto/.pyenv/versions/patsy/lib/python3.6/site-packages/patsy/parse_formula.py", line 94, in _tokenize_formula
    yield _read_python_expr(it, end_tokens)
  File "/home/alberto/.pyenv/versions/patsy/lib/python3.6/site-packages/patsy/parse_formula.py", line 44, in _read_python_expr
    for pytype, token_string, origin in it:
  File "/home/alberto/.pyenv/versions/patsy/lib/python3.6/site-packages/patsy/util.py", line 332, in next
    return six.advance_iterator(self._it)
  File "/home/alberto/.pyenv/versions/patsy/lib/python3.6/site-packages/patsy/tokens.py", line 35, in python_tokenize
    assert pytype not in (tokenize.NL, tokenize.NEWLINE)
AssertionError
`

**Comment by njsmith** [comment]
This was fixed by #131; just need to do a release, which I'm working on now.
