### ISSUE TITLE
0.5.3: documentation build fails with sphinx 6.2.1

### ISSUE THREAD

**Issue by kloczek** [pydata/patsy#193]
Looks like doc/content needs to be updated for sphinx +6.x
```console
+ /usr/bin/sphinx-build -n -T -b man doc build/sphinx/man
Running Sphinx v6.2.1
python exec: /usr/bin/python3
sys.path: ['/usr/bin', '/usr/lib64/python38.zip', '/usr/lib64/python3.8', '/usr/lib64/python3.8/lib-dynload', '/home/tkloczko/.local/lib/python3.8/site-packages', '/usr/lib64/python3.8/site-packages', '/usr/lib/python3.8/site-packages']
numpy: 1.24.3, /usr/lib64/python3.8/site-packages/numpy/__init__.py
matplotlib: 3.6.3, /usr/lib64/python3.8/site-packages/matplotlib/__init__.py
ipython: 8.12.0, /usr/lib/python3.8/site-packages/IPython/__init__.py
making output directory... done

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 243, in __init__
    self.config.setup(self)
  File "/home/tkloczko/rpmbuild/BUILD/patsy-0.5.3/doc/conf.py", line 70, in setup
    app.add_javascript("show-code.js")
AttributeError: 'Sphinx' object has no attribute 'add_javascript'

Exception occurred:
  File "/home/tkloczko/rpmbuild/BUILD/patsy-0.5.3/doc/conf.py", line 70, in setup
    app.add_javascript("show-code.js")
AttributeError: 'Sphinx' object has no attribute 'add_javascript'
The full traceback has been saved in /tmp/sphinx-err-8x1irlvx.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by matthewwardrop** [comment]
Hi @kloczek ! Thanks for reporting. However, given that this project is frozen, documentation is unlikely to ever be updated, and migrating to Sphinx 6 would require migrating all Python 2 code, I'm just going to let this lie.
